jwt:
  secret: NESTJSBACKENDAUTHT@--
  token_expiry: 30d

node_env: development

frontend:
  base_url: https://opinions.secondaid.in

app:
  local: https://opinions-api.secondaid.in

organisation:
  has_organisation: true

otp:
  length: 6

# sms:
#   username: guideme.trans
#   password: 3R1rt
#   senderId: GUIDSM
#   unicode: false
#   dltContentId: '1007165665000180033'

typeorm:
  port: 3306
  host: localhost
  synchronize: true
  logging: true
  connection: mysql
  username: root
  password: "@Ctive123gcs"
  database: second_opinion
  secure: true

storage:
  disk: local

aws:
  accessKeyId: 921ad53cb68170ebda2771d35670524a
  secretAccessKey: 5fd3a19e71be31dca19ed2736b53de6e615ee1db48681c68e54887255d870f45
  endpoint: https://52d45400e195803bd6da970dc7961d23.r2.cloudflarestorage.com
  bucket_name: test-bucket

allowed_file_size: 1000000

date_format: "LLL yy"

time_format: "hh:mm a"

mail:
  host: smtp.zoho.com
  port: 587
  user: contact.us@craftnotion.com
  password: "@Ctive123gcs"
  from: contact.us@craftnotion.com

# App branding for emails
name: Second Opinion
background: "#f8f9fa"
color: "#007bff"

frontend_url: http://localhost:3000

logo: https://seniorexperts.in/home/images/logo.png

email:
  admin_email: arekapudikrishnachaitanya@gmail.com